file_storage/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('login.urls'))
]

login/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('login_user', views.login_user, name='login'),
    path('logout', views.logut_user, name='logout'),
    path('register', views.register_user, name='register'),
    # path('register/login', views.register_user, name='register_login')
]

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', login_required(views.main_page), name='home'),
    path('all_files', login_required(views.all_files), name='all_f'),
    path('all_notes', login_required(views.all_notes), name='all_n'),
    path('pictures', login_required(views.pictures), name='pictures'),
    path('files', login_required(views.files), name='files'),
    path('links', login_required(views.links), name='links'),
    path('notes', login_required(views.notes), name='notes'),
    path('all_files/download/<file_id>', login_required(views.file_download), name='download'),
    path('notes/delete/<note_id>', login_required(views.notes_delete), name='note_delete'),
    path('files/delete/<file_id>', login_required(views.file_delete), name='file_delete'),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=60)
    last_name = forms.CharField(max_length=60)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:

            messages.success(request, ("there was an error"))
            return redirect('login')
    else:
        return render(request, 'login/login.html', {})

def logut_user(request):
    logout(request)
    return redirect('login')

def register_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username= form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Registr succes"))
            return redirect('/')
        else:
            print(form.errors)

    else:
        form = RegisterUserForm()

    return render(request, 'login/registartion.html', {"form":form})

login/templates/login/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'login/css/login.css' %}">
    <title>Login</title>
</head>
<body>
     {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
     {% endif %}

     <section class='login' id='login'>
        <div class='head'>
            <h1 class='company'>Storage space</h1>
        </div>
        <p class='msg'>Welcome</p>
        <div class='form'>
            <form action="" method="post">
                {% csrf_token %}
                <input type="text" placeholder="Enter Username" name="username" class='text' id='username' required><br>
                <input type="password" placeholder="Enter Password" name="password" class='password' required><br>
                <button class='btn-login' id='do-login' type="submit">Login</button>
                <a href="{% url 'register' %}" class='signup'>Signup</a>
                <a href="#" class='forgot'>Forgot?</a>
            </form>
        </div>
    </section>


</body>
</html>

login/templates/login/registartion.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'login/css/registration.css' %}">
    <title>Registr</title>
</head>
<body>
    <div class="form-container">
        <h2>Registration Form</h2>
        {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        {% endif %}
        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            <div class="container">
                <input type="text" class="form-input" placeholder="First Name" name="first_name" maxlength="60" required id="id_first_name">
                <input type="text" class="form-input" placeholder="Last Name" name="last_name" maxlength="60" required id="id_last_name">
                <input type="email" class="form-input" placeholder="Email" name="email" required id="id_email">
                <input type="text" class="form-input" placeholder="Username" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
                <input type="password" class="form-input" placeholder="Password" name="password1" autocomplete="new-password" required="" id="id_password1">
                <input type="password" class="form-input" placeholder="Password Confirmation" name="password2" autocomplete="new-password" required="" id="id_password2">
                <button type="submit" class="form-submit">Login</button>
            </div>
        </form>
    </div>

</body>
</html>