file_storage/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('login.urls'))
]

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', login_required(views.main_page), name='home'),
    path('all_files', login_required(views.all_files), name='all_f'),
    path('all_notes', login_required(views.all_notes), name='all_n'),
    path('pictures', login_required(views.pictures), name='pictures'),
    path('files', login_required(views.files), name='files'),
    path('links', login_required(views.links), name='links'),
    path('notes', login_required(views.notes), name='notes'),
    path('all_files/download/<file_id>', login_required(views.file_download), name='download'),
    path('notes/delete/<note_id>', login_required(views.notes_delete), name='note_delete'),
    path('files/delete/<file_id>', login_required(views.file_delete), name='file_delete'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# import time
#
# t = time.localtime()
# current_time = time.strftime("%H:%M:%S", t)


class Note(models.Model):
    user_choice = [('Link', 'Link'), ('Note', 'Note')]
    file_type = models.CharField(max_length=15, choices=user_choice, default='Link')
    heading = models.CharField(max_length=30, null=True)
    user_data = models.TextField(max_length=1500)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    datetime = models.DateTimeField(auto_now=True)


#Model for files and pics
class Document(models.Model):
    user_choice = [('Photo', 'Photo'), ('Document', 'Document')]
    file_type = models.CharField(max_length=15, choices=user_choice, default='Link')
    document = models.FileField(upload_to='documents/')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    datetime = models.DateTimeField(auto_now_add=True)

main/forms.py
from .models import Document, Note
from django import forms


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document', 'file_type',)


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('heading', 'user_data', 'file_type',)

main/views.py
from django.shortcuts import render, redirect
from .forms import DocumentForm, NoteForm
from .models import Document, Note
from django.contrib.auth.decorators import login_required
from random import shuffle
from django.http import FileResponse
import os
from django.http import StreamingHttpResponse
from wsgiref.util import FileWrapper #django >1.8
from django.conf import settings
from django.shortcuts import HttpResponseRedirect


@login_required()
def main_page(request):
    last_5 = Document.objects.all().filter(user_id=request.user).order_by('-id')[:5]

    files_count = len(Document.objects.all().filter(user_id=request.user, file_type="Document"))
    pics_count = len(Document.objects.all().filter(user_id=request.user, file_type="Photo"))
    links_count = len(Note.objects.all().filter(user_id=request.user, file_type="Link"))
    notes_count = len(Note.objects.all().filter(user_id=request.user, file_type="Note"))


    if request.method == 'POST':
        print("THIS IS POST", request.POST)

        post_request = dict(request.POST)
        print(post_request['file_type'])
        if post_request['file_type'][0] == "Document" or post_request['file_type'][0] == "Photo":

            form = DocumentForm(request.POST, request.FILES)
            if form.is_valid():
                print("valid")
                for f in request.FILES.getlist('document'):
                    instance = Document(file_type=request.POST.get('file_type'), document=f, user=request.user)
                    instance.save()

                return redirect('/')
            else:
                print(form.errors)
                return redirect('/')

        elif post_request['file_type'][0] == "Link" or post_request['file_type'][0] == "Note":
            form = NoteForm(request.POST, request.FILES)
            if form.is_valid():
                print("second valid")
                obj = form.save(commit=False)
                obj.user = request.user
                obj.save()
                return redirect('/')
            else:
                print(form.errors)
                return redirect('/')
    else:
       form = DocumentForm()

    return render(request, 'main/home.html', {"recent":last_5, "files": files_count, "photos": pics_count, "links":links_count, "notes":notes_count})


def all_files(request):
    all_files = Document.objects.all().filter(user_id=request.user)


    return render(request, 'main/all_files.html', {"files":all_files})




def file_download(request, file_id):
    obj = Document.objects.filter(id=file_id, user_id=request.user.id).first()
    if obj:
        file_path = os.path.join(settings.MEDIA_ROOT, obj.document.name)
        filename = os.path.basename(file_path)
        chunk_size = 8192
        response = StreamingHttpResponse(
            FileWrapper(open(file_path, 'rb'), chunk_size),
            content_type="application/octet-stream"
        )
        response['Content-Length'] = os.path.getsize(file_path)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response
    else:
        print(request.user.id, file_id)
        return redirect('/')


def all_notes(request):
    notes_obj = Note.objects.all().filter(user_id=request.user)
    return render(request, 'main/all_notes.html', {"notes":notes_obj})


def pictures(request):
    all_pictures = Document.objects.all().filter(user_id=request.user, file_type="Photo")
    return render(request, 'main/all_files.html', {"files": all_pictures})


def files(request):
    all_files = Document.objects.all().filter(user_id=request.user, file_type="Document")
    return render(request, 'main/all_files.html', {"files": all_files})


def links(request):
    links_obj = Note.objects.all().filter(user_id=request.user, file_type="Link")
    return render(request, 'main/all_notes.html', {"notes":links_obj})


def notes(request):
    note_obj = Note.objects.all().filter(user_id=request.user, file_type="Note")
    return render(request, 'main/all_notes.html', {"notes":note_obj})


def notes_delete(request, note_id):
    note_obj = Note.objects.filter(id=note_id)
    note_obj.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def file_delete(request, file_id):
    note_obj = Document.objects.filter(id=file_id)
    note_obj.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

main/templates/main/all_files.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>File</th>
                    <th>Size</th>
                    <th>Added</th>
                    <th>Download</th>
                </tr>
            </thead>
            <tbody>
                {% for file in files %}
                    <tr>
                        <td>{{ file.document.name | cut:'documents/' }}</td>
                        <td>{{ file.document.size | filesizeformat}}</td>
                        <td>{{ file.datetime }}</td>
{#                        <td><a href="{% url 'download' file_id=file.id %}"><i class="fa-solid fa-download"></i></a></td>#}
                        <td>
                            <i class="fa-solid fa-ellipsis-vertical" id="menu-icon-{{ forloop.counter }}"></i>
                            <div id="dropdown-menu-{{ forloop.counter }}" class="hidden">
                              <a href="{% url 'download' file_id=file.id %}"><i class="fa-solid fa-download"></i></a>
                              <a href="{% url 'file_delete' file.id %}">Delete</a>
                            </div>
                        </td>
                    <tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="{% static 'main/js/three_dots_menu.js' %}"></script>




{% endblock %}

main/templates/main/all_notes.html
{% extends 'main/layout.html' %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'main/css/all_notes.css' %}">{% endblock %}

{% block content %}
{% for note in notes %}
    <div class="folder-wrapper" data-popup="popup{{ forloop.counter }}">
        <div class="folder-info">
            <div class="icon-delete">
                <i class="fa-solid fa-folder-closed fa-2x folder-icon"></i>
                <a href="{% url 'note_delete' note.id %}"><i class="fa-solid fa-xmark"></i></a>
            </div>
            <h3 class="folder-name">{{ note.heading }}</h3>
        </div>
    </div>
{% endfor %}
{% endblock %}

{% block popups %}
{% for note in notes %}
    <div id="popup{{ forloop.counter }}" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>{{ note.heading }}</h2>
            {% if note.file_type == "Link" %}
                <a href="{{ note.user_data }}" target="_blank"><p>{{ note.user_data }}</p></a>
            {% else %}
                <p>{{ note.user_data }}</p>
            {% endif %}
        </div>
    </div>
{% endfor %}
<script src="{% static 'main/js/all_notes_popups.js' %}"></script>
{% endblock %}

main/templates/main/file_upload.html
{% load static %}
{% block styles %}<link rel="stylesheet" href="{% static 'main/css/file_upload.css' %}">{% endblock %}
<!-- Drop Zone Container -->
<div class="file-upload-wrapper" id="file-popup">
    <div class="file-upload-content" id="doc-popup-content">
        <form class="doc-form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="file-popup" id="drop-zone-container">
                <span id="doc-close" class="close">&times;</span>
                <div class="popup-content" id="drop-zone">
                    <p id="drop-zone-text">Drop files here or click to browse</p>
                    <div id="file-preview">
                        <ul id="file-names"></ul>
                    </div>
                    <input name="document" type="file" id="file-input" multiple>
                    <input name="file_type" type="hidden" id="myField" value="" />
                </div>

                <button type="submit">Upload</button>

            </div>

        </form>
    </div>
</div>
<script src="{% static 'main/js/file_upload.js' %}"></script>

main/templates/main/home.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
<div class="main-section">
    <div class="files-icons">
        <div class="icon-wrapper-main"><i class="fa-solid fa-image fa-lg"><span class="upper">{{ photos }} photos</span></i></div>
        <div class="icon-wrapper-main"><i class="fa-solid fa-folder fa-lg"><span class="upper">{{ files }} files</span></i></div>
        <div class="icon-wrapper-main"><i class="fa-solid fa-link fa-lg"><span class="upper">{{ links }} links</span></i></div>
        <div class="icon-wrapper-main"><i class="fa-solid fa-note-sticky fa-lg"><span class="upper">{{ notes }} notes</span></i></div>
    </div>
    <div class="folders">
        <h3>Folders</h3>
        <div class="folders-block">
            <div class="folder-wrapper">
                <div class="folder-info">
                    <i class="fa-solid fa-folder-closed fa-2x folder-icon"></i>
                    <h3 class="folder-name">Theme</h3>
                    <span class="file-amount">File amount</span>
                </div>
            </div>
            <div class="folder-wrapper">
                <div class="folder-info">
                    <i class="fa-solid fa-folder-closed fa-2x folder-icon"></i>
                    <h3 class="folder-name">Theme</h3>
                    <span class="file-amount">File amount</span>
                </div>
            </div>
            <div class="folder-wrapper">
                <div class="folder-info">
                    <i class="fa-solid fa-folder-closed fa-2x folder-icon"></i>
                    <h3 class="folder-name">Theme</h3>
                    <span class="file-amount">File amount</span>
                </div>
            </div>
            <div class="folder-wrapper">
                <div class="folder-info">
                    <i class="fa-solid fa-folder-closed fa-2x folder-icon"></i>
                    <h3 class="folder-name">Theme</h3>
                    <span class="file-amount">File amount</span>
                </div>
            </div>
            <div class="folder-wrapper">
                <div class="folder-info">
                    <i class="fa-solid fa-folder-closed fa-2x folder-icon"></i>
                    <h3 class="folder-name">Theme</h3>
                    <span class="file-amount">File amount</span>
                </div>
            </div>
            <div class="folder-wrapper">
                <div class="folder-info">
                    <i class="fa-solid fa-folder-closed fa-2x folder-icon"></i>
                    <h3 class="folder-name">Theme</h3>
                    <span class="file-amount">File amount</span>
                </div>
            </div>
            <div class="folder-wrapper">
                <div class="folder-info">
                    <i class="fa-solid fa-folder-closed fa-2x folder-icon"></i>
                    <h3 class="folder-name">Theme</h3>
                    <span class="file-amount">File amount</span>
                </div>
            </div>

        </div>
    </div>
    <div class="files-section">
        <h3>Files</h3>
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>File</th>
                        <th>Size</th>
                        <th>Added</th>
                        <th>Download</th>
                    </tr>
                </thead>
                <tbody>
                    {% for file in recent %}
                    <tr>
                        <td>{{ file.document.name | cut:'documents/' }}</td>
                        <td>{{ file.document.size | filesizeformat}}</td>
                        <td>{{ file.datetime }}</td>
                        <td>
                            <i class="fa-solid fa-ellipsis-vertical" id="menu-icon-{{ forloop.counter }}"></i>
                            <div id="dropdown-menu-{{ forloop.counter }}" class="hidden">
                              <a href="{% url 'download' file_id=file.id %}"><i class="fa-solid fa-download"></i></a>
                              <a href="{% url 'file_delete' file.id %}">Delete</a>
                            </div>
                        </td>
                    <tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="storage-section">
    <div class="form-floating">
        <select onchange="a()" class="form-select" id="floatingSelect" aria-label="Floating label select example">
            <option id="none" selected="selected" disabled value="">None</option>
            <option  id="photo" value="Photo">Photo</option>
            <option id="document" value="Document">Document</option>
            <option id="link" value="Link" class="open-popup" data-popup="link">Link</option>
            <option id="note" value="Note">Note</option>
        </select>
        <label for="floatingSelect">Select file type</label>
    </div>
</div>

<script src="{% static 'main/js/upload_popup.js' %}"></script>
<script src="{% static 'main/js/three_dots_menu.js' %}"></script>

{% endblock %}

{% block file_popup %}
{% include 'main/file_upload.html' %}
{% endblock %}

{% block note_popup %}
{% include 'main/note_upload.html' %}
{% endblock %}

main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'main/css/layout.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block styles %}{% endblock %}
{#    <link rel="stylesheet" href="{% static 'main/css/file_upload.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'main/css/note_upload.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'main/css/all_notes.css' %}">#}

    <script src="https://kit.fontawesome.com/ee07bab358.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
</head>
<body>

    <div class="content">
        <header class="blur">
            <div class="header-container">
                <div class="logo-section">
{#                    <img class="logo" src="https://www.freepnglogos.com/uploads/server-png/server-icon-download-icons-17.png" alt="">#}
                    <h3 class="app-name">server</h3>
                </div>
                <div class="search-bar">
                    <input class="search-bar" type="text" placeholder="Search files...">
                </div>
                <div class="profile-logo">
                    {% if user.is_authenticated %}
                        <img class="profile-pic" src="https://images.unsplash.com/photo-1628563694622-5a76957fd09c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE2fHx8ZW58MHx8fHw%3D&w=1000&q=80" alt="">
                        <div class="user-info">
                            <span class="name">{{ user.first_name }} {{ user.last_name }}</span>
                            <span class="email">{{ user.email }}</span>

                        </div>
                        <div class="sidebar_toggler">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    {% else %}
                        <a href="{% url 'login' %}">Login</a>
                        <a href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </header>

        <div class="main-container blur">
            <aside id="sidebar"> {#class="left-menu-bar"#}
                <div class="sidebar_content sidebar_body" {#class="left-menu-bar-icons"#}>
                    <nav class="side_navlinks">
                        <div class="upper-icons">
                            <a href="{% url 'home' %}"><div class="icon-wrapper"><i class="fa-solid fa-house fa-lg"></i><span class="icon-heading">Dashboard</span></div></a>
                            <a href="{% url 'all_f' %}"><div class="icon-wrapper"><i class="fa-solid fa-border-none fa-lg"></i><span class="icon-heading">All files</span></div></a>
                            <a href="{% url 'all_n' %}"><div class="icon-wrapper"><i class="fa-solid fa-file fa-lg"></i><span class="icon-heading">All notes</span></div></a>
                            <div class="icon-wrapper"><i class="fa-solid fa-heart fa-lg"></i><span class="icon-heading">Favorites</span></div>
                        </div>
                       <div class="lower-icons">
                           <a href="{% url 'pictures' %}"><div class="icon-wrapper"><i class="fa-solid fa-image fa-lg"></i><span class="icon-heading">Pictures</span></div></a>
                           <a href="{% url 'files' %}"><div class="icon-wrapper"><i class="fa-solid fa-folder fa-lg"></i><span class="icon-heading">Files</span></div></a>
                           <a href="{% url 'links' %}"><div class="icon-wrapper"><i class="fa-solid fa-link fa-lg"></i><span class="icon-heading">Links</span></div></a>
                           <a href="{% url 'notes' %}"><div class="icon-wrapper"><i class="fa-solid fa-note-sticky fa-lg"></i><span class="icon-heading">Notes</span></div></a>
                       </div>
                    </nav>
                </div>
            </aside>
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% block popups %}
    {% endblock %}

    {% block file_popup %}
    {% endblock %}

    {% block note_popup %}
    {% endblock %}
{#    {% include 'main/file_upload.html' %}#}
{#    {% include 'main/note_upload.html' %}#}
    <script src="{% static 'main/js/sidebar.js' %}"></script>

</body>
</html>

main/templates/main/note_upload.html
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'main/css/note_upload.css' %}">{% endblock %}

<div class="note-popup-wrapper" id="note-popup">
    <div class="form-group" id="note-popup-content">
        <span id="note-close" class="close">&times;</span>
        <form method="post">
        {% csrf_token %}
            <label for="id_heading">Heading:</label>
            <input type="text" name="heading" class="form-control" maxlength="30" required="" id="id_heading">
            <label for="id_user_data">Data:</label>
            <textarea class="form-control" name="user_data" cols="40" rows="10" maxlength="1500" required="" id="id_user_data"></textarea>
            <input name="file_type" type="hidden" id="myField1" value="" />
            <button type="submit">Upload</button>
      </form>
    </div>
</div>